name: "quiz_factory"
version: "1.0.0"
config-version: 2
profile: "quiz_factory"

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  quiz_factory:
    +materialized: view
    staging:
      +schema: tmp
    marts:
      +schema: marts

vars:
  reporting_timezone: "UTC"
  incremental_lookback_days: 2
  credits_attribution_lookback_days: 30
  credits_guard_lookback_days: 30
  credits_guard_overage_allowance: 5
  offer_key_required_cutoff_date: "2100-01-01"
