name: "quiz_factory"
version: "1.0.0"
config-version: 2
profile: "quiz_factory"

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  quiz_factory:
    +materialized: view
    staging:
      +schema: tmp
    marts:
      +schema: marts

vars:
  reporting_timezone: "UTC"
