quiz_factory:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('DBT_BIGQUERY_PROJECT', 'dummy-project') }}"
      dataset: "{{ env_var('DBT_BIGQUERY_DATASET', 'dummy_dataset') }}"
      location: "{{ env_var('DBT_BIGQUERY_LOCATION', 'US') }}"
      threads: 1
      timeout_seconds: 300
